### ISSUE TITLE
Convert UserAccountController to a resource controller

### ISSUE THREAD

**Issue by tft-kaare** [TromsFylkestrafikk/ragnarok#23]
Convert everything related to user account to a resource controller. Some calls are from the web.php and some from the api.php space. This must be combined as all calls deliver back-end json data.

Handling permissions for each call can be extracted to policies. Read up on https://laravel.com/docs/10.x/authorization.

**Comment by tft-kyrre** [comment]
Ready for review.

**Comment by tft-kaare** [comment]
Much cleaner! Thx :-)
