### ISSUE TITLE
Populate sink overview with valid data

### ISSUE THREAD

**Issue by tft-kaare** [TromsFylkestrafikk/ragnarok#36]
## Problem / motivation

- The 'last import' and 'last import status' columns are empty.
- The import button does not import. It operates on an import model that currently is not in use
- It feels empty. Some additional information should be present, like data storage, number of chunks, etc.

## Suggested resolution
- [x] Populate last import and its status with the most recently imported chunk.
- [x] Make the import button available only if there are something new to import. This will invoke a new background batched job, so hiding this button while the batch is in progress must be dealt with
- [ ] Adding chunk count … dunnot about this. But the actual storage per sink is valuable information.

**Comment by tft-kyrre** [comment]
The "New chunk" count is incorrect when there's many new chunks available, spanning multiple pages.

**Comment by tft-kaare** [comment]
@tft-kyrre, I added a hard limit of 10 chunks to be considered 'new'. The idea was that we should avoid having to import the entire data set on this operation. It is ment to be a light-weight "keep up with recent changes".

But I'm open to other suggestions how this should work.

**Comment by tft-kyrre** [comment]
Wouldn't it be better to have all chunks downloaded (and imported) automatically on a daily basis, like a cron job? Relying on users doing this manually may lead to data gaps and makes the UI unnecessarily complex, I think.
